version: '3.8'

services:
  # Наша База Даних
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-vin_matrix_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-super_secret_pass}
    ports:
      - "5432:5432"

  # Наш Python Бекенд
  backend:
    build: 
      context: ./backend
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-django-insecure-key}
      - USE_POSTGRES=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-vin_matrix_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-super_secret_pass}

volumes:
  postgres_data:
