# Generated by Django 5.1.2 on 2026-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_merge_agent_write_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentcompanysettings",
            name="default_visit_duration_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
