import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "vin_matrix.settings")
django.setup()
from django.db import connection

# --- Існуючі таблиці ---
query_employee = "CREATE TABLE IF NOT EXISTS core_employee (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role varchar(20) NOT NULL, company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED, user_id integer NOT NULL UNIQUE REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED);"
query_category = "CREATE TABLE IF NOT EXISTS core_category (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(255) NOT NULL, company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED);"
query_inventory = "CREATE TABLE IF NOT EXISTS core_inventoryitem (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, brand varchar(100) NOT NULL, article varchar(100) NOT NULL, name text NOT NULL, quantity integer NOT NULL DEFAULT 0, buy_price numeric(10, 2) NOT NULL, category_id bigint REFERENCES core_category(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED, company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED);"
query_supplier = "CREATE TABLE IF NOT EXISTS core_supplier (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(255) NOT NULL, api_key varchar(255), price_file varchar(100), company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED);"

# --- НОВІ ТАБЛИЦІ (Довідник послуг та Послуги у візиті) ---
query_servicecatalog = "CREATE TABLE IF NOT EXISTS crm_servicecatalog (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(255) NOT NULL, default_price numeric(10, 2) NOT NULL, is_active boolean NOT NULL, company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED);"
# Зверни увагу: visit_id посилається на crm_visit
query_visitservice = "CREATE TABLE IF NOT EXISTS crm_visitservice (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, custom_name varchar(255) NOT NULL, price numeric(10, 2) NOT NULL, quantity numeric(5, 1) NOT NULL, service_catalog_id bigint REFERENCES crm_servicecatalog(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED, visit_id bigint NOT NULL REFERENCES crm_visit(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED);"


queries_alter = [
    # Старі колонки
    "ALTER TABLE core_visit ADD COLUMN updated_at timestamp with time zone;",
    "ALTER TABLE core_visit ADD COLUMN scheduled_datetime timestamp with time zone;",
    "ALTER TABLE core_orderpart ADD COLUMN status varchar(20) DEFAULT 'WAITING';",
    "ALTER TABLE core_orderservice ADD COLUMN status varchar(20) DEFAULT 'PENDING';",
    "ALTER TABLE core_visit ADD COLUMN comment text;",
    "ALTER TABLE core_visit ADD COLUMN vin_code varchar(17);",
    "ALTER TABLE core_supplier ADD COLUMN warehouse_prefs jsonb DEFAULT '[]'::jsonb;",
    "ALTER TABLE core_company ADD COLUMN euro_rate numeric(6, 2) DEFAULT 42.00;",
    "ALTER TABLE core_company ADD COLUMN business_type varchar(20) DEFAULT 'sto';",
    "ALTER TABLE core_visit ADD COLUMN delivery_type varchar(50) DEFAULT 'pickup';",
    "ALTER TABLE core_visit ADD COLUMN delivery_data text;",
    "ALTER TABLE core_visit ADD COLUMN payment_status varchar(50) DEFAULT 'unpaid';",
    "ALTER TABLE core_visit ADD COLUMN prepayment_amount numeric(10, 2) DEFAULT 0;",
    "ALTER TABLE core_employee ADD COLUMN can_create_visits boolean DEFAULT false;",
    "ALTER TABLE core_employee ADD COLUMN can_view_finances boolean DEFAULT false;",
    
    # --- НОВІ КОЛОНКИ ---
    # Додаємо mileage (пробіг) у crm_visit (або core_visit, залежно від того, як таблиця створена в БД)
    "ALTER TABLE crm_visit ADD COLUMN mileage integer;",
    "ALTER TABLE core_visit ADD COLUMN mileage integer;"
]

print("Починаємо перевірку бази даних PostgreSQL...")
with connection.cursor() as cursor:
    try: cursor.execute(query_employee); print("Таблиця core_employee ОК.")
    except Exception as e: print(e)
    
    try: cursor.execute(query_category); print("Таблиця core_category ОК.")
    except Exception as e: print(e)
    
    try: cursor.execute(query_inventory); print("Таблиця core_inventoryitem ОК.")
    except Exception as e: print(e)
    
    try: cursor.execute(query_supplier); print("Таблиця core_supplier ОК.")
    except Exception as e: print(e)
    
    try: cursor.execute(query_servicecatalog); print("Таблиця crm_servicecatalog ОК.")
    except Exception as e: print(e)
        
    try: cursor.execute(query_visitservice); print("Таблиця crm_visitservice ОК.")
    except Exception as e: print(e)

    for q in queries_alter:
        try: cursor.execute(q)
        except Exception: pass

print("Оновлення бази завершено!")
