import os
import django

# Підключаємо налаштування Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "vin_matrix.settings")
django.setup()

from django.db import connection

# SQL-команда, яка жорстко створює таблицю для майстрів
query = """
CREATE TABLE IF NOT EXISTS core_employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar(20) NOT NULL,
    company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED,
    user_id integer NOT NULL UNIQUE REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
"""

print("Починаємо перевірку таблиці Майстрів...")
with connection.cursor() as cursor:
    try:
        cursor.execute(query)
        print("Таблиця core_employee успішно перевірена/створена!")
    except Exception as e:
        print(f"Помилка: {e}")
