import os
import django

# Підключаємо налаштування Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "vin_matrix.settings")
django.setup()

from django.db import connection

# 1. Запит для таблиці Майстрів (старий)
query_employee = """
CREATE TABLE IF NOT EXISTS core_employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role varchar(20) NOT NULL,
    company_id bigint NOT NULL REFERENCES core_company(id) DEFERRABLE INITIALLY DEFERRED,
    user_id integer NOT NULL UNIQUE REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
);
"""

# 2. Запити для нових колонок візиту та запчастин (нові)
queries_alter = [
    "ALTER TABLE core_visit ADD COLUMN updated_at timestamp with time zone;",
    "ALTER TABLE core_visit ADD COLUMN scheduled_datetime timestamp with time zone;",
    "ALTER TABLE core_orderpart ADD COLUMN status varchar(20) DEFAULT 'WAITING';",
    "ALTER TABLE core_orderservice ADD COLUMN status varchar(20) DEFAULT 'PENDING';"
]

print("Починаємо перевірку бази даних PostgreSQL...")
with connection.cursor() as cursor:
    # Перевіряємо майстрів
    try:
        cursor.execute(query_employee)
        print("Таблиця core_employee перевірена.")
    except Exception as e:
        print(f"Помилка Employee: {e}")
        
    # Додаємо колонки дат і статусів
    for q in queries_alter:
        try:
            cursor.execute(q)
            print("УСПІШНО: Колонку додано!")
        except Exception as e:
            print("ПРОПУЩЕНО: (Колонка вже є)")

print("Оновлення бази завершено!")
