# Generated by Django 5.1.2 on 2026-06-14 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_merge_production_setup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("store", "Магазин"),
                            ("sto", "СТО"),
                            ("both", "Обидва режими"),
                            ("system", "Система"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("group", models.CharField(max_length=60)),
                ("key", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("color", models.CharField(default="slate", max_length=30)),
                ("icon", models.CharField(blank=True, max_length=40, null=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "semantic_role",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["group", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ComplexPartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("article", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "buy_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sell_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                ("supplier", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComplexServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CRMClientStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("plate", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новий"),
                            ("active", "Активний"),
                            ("regular", "Постійний"),
                            ("sleeping", "Сплячий"),
                            ("problem", "Проблемний"),
                            ("vip", "VIP"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CRMCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("plate", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("called", "Дзвонили клієнту"),
                            ("no_answer", "Клієнт не відповів"),
                            ("call_back", "Домовились передзвонити"),
                            ("refused", "Клієнт відмовився"),
                            ("thinking", "Клієнт думає"),
                            ("agreed", "Клієнт погодився"),
                        ],
                        default="called",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CRMServiceReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("plate", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("oil", "Заміна масла"),
                            ("filters", "Фільтри"),
                            ("brakes", "Гальма"),
                            ("tires", "Сезонна заміна шин"),
                            ("maintenance", "ТО"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("due_mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активне"),
                            ("done", "Виконано"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["status", "due_date", "due_mileage", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("plate", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нова"),
                            ("in_progress", "В роботі"),
                            ("done", "Виконана"),
                            ("overdue", "Прострочена"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceComplex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StoExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Оренда"),
                            ("utilities", "Комунальні"),
                            ("admin_salary", "Зарплата адміністратора / персоналу"),
                            ("tools", "Інструмент"),
                            ("equipment", "Обладнання"),
                            ("equipment_repair", "Ремонт обладнання"),
                            ("consumables", "Витратні матеріали"),
                            ("marketing", "Маркетинг / реклама"),
                            ("taxes", "Податки"),
                            ("bank_fees", "Банківські комісії"),
                            ("delivery", "Доставка / логістика"),
                            ("fuel", "Пальне"),
                            ("software", "Програми / підписки"),
                            ("cleaning", "Прибирання / господарські витрати"),
                            ("other", "Інше"),
                        ],
                        default="other",
                        max_length=60,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Готівка"),
                            ("card", "Картка"),
                            ("bank", "Рахунок / банк"),
                            ("other", "Інше"),
                        ],
                        default="cash",
                        max_length=40,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurring_period",
                    models.CharField(
                        choices=[
                            ("none", "Разова витрата"),
                            ("weekly", "Щотижня"),
                            ("monthly", "Щомісяця"),
                            ("yearly", "Щороку"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VehicleRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("plate", models.CharField(blank=True, max_length=20, null=True)),
                ("car", models.CharField(blank=True, max_length=160, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("due_mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активна"),
                            ("done", "Виконана"),
                            ("cancelled", "Скасована"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("number", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "number", "id"],
            },
        ),
        migrations.RenameIndex(
            model_name="inventoryitem",
            new_name="core_invent_company_5c1d33_idx",
            old_name="core_invent_company_4bf5d1_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="core_stockm_company_e2403f_idx",
            old_name="core_stockm_company_f8b9e7_idx",
        ),
        migrations.AddField(
            model_name="company",
            name="document_requisites",
            field=models.TextField(
                blank=True, null=True, verbose_name="Document requisites"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="document_signature",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Document signature"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="document_warranty_text",
            field=models.TextField(blank=True, null=True, verbose_name="Warranty text"),
        ),
        migrations.AddField(
            model_name="employee",
            name="commission_percent",
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_salary_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="parts_commission_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="payout_period",
            field=models.CharField(
                choices=[
                    ("daily", "Щодня"),
                    ("weekly", "Щотижня"),
                    ("monthly", "Щомісяця"),
                    ("custom", "Довільний період"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary_scheme",
            field=models.CharField(
                choices=[
                    ("services_only", "Відсоток тільки від робіт"),
                    (
                        "services_and_parts_profit",
                        "Відсоток від робіт + маржі запчастин",
                    ),
                    ("order_profit", "Відсоток від прибутку замовлення"),
                    ("fixed", "Фіксована сума"),
                ],
                default="services_only",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="orderpart",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name="orderpart",
            name="supplier_color",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="commission_base",
            field=models.CharField(
                choices=[
                    ("services_only", "Тільки роботи"),
                    ("services_and_parts_profit", "Роботи + маржа запчастин"),
                    ("order_profit", "Прибуток замовлення"),
                    ("fixed", "Фіксована сума"),
                ],
                default="services_only",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="commission_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="mechanic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="billing_status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("payment_due_soon", "Payment due soon"),
                    ("grace", "Grace period"),
                    ("blocked", "Blocked"),
                    ("manual_free", "Manual free access"),
                ],
                default="trial",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="blocked_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="grace_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="last_payment_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="last_payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="payment_notice_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="subscription_price",
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="subscription_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="subscription_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformclient",
            name="trial_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="api_login",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="api_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="api_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="api_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="api_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="api_type",
            field=models.CharField(
                choices=[
                    ("custom", "Інший / Excel"),
                    ("vesna", "Vesna-auto"),
                    ("omega", "Omega"),
                    ("tehnomir", "Техномир"),
                    ("bm", "BM Parts"),
                    ("utr", "Юнік Трейд"),
                ],
                default="custom",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="browser_fingerprint",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="responsible_mechanic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="business_type",
            field=models.CharField(default="sto", max_length=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="document_footer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Document footer"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="euro_rate",
            field=models.DecimalField(decimal_places=2, default=42.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="company",
            name="global_margin_percent",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_logos/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Company name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="platformclient",
            name="is_access_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="platformclient",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="companyoption",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="crmclientstatus",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_client_statuses",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="crmclientstatus",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_crm_client_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmcommunication",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_communications",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="crmcommunication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_crm_communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmcommunication",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_communications",
                to="core.visit",
            ),
        ),
        migrations.AddField(
            model_name="crmservicereminder",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_service_reminders",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="crmservicereminder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_crm_service_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmservicereminder",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_service_reminders",
                to="core.visit",
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_tasks",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_crm_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crmtask",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_tasks",
                to="core.visit",
            ),
        ),
        migrations.AddField(
            model_name="servicecomplex",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_complexes",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="complexserviceitem",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="core.servicecomplex",
            ),
        ),
        migrations.AddField(
            model_name="complexpartitem",
            name="complex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="core.servicecomplex",
            ),
        ),
        migrations.AddField(
            model_name="stoexpense",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sto_expenses",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="stoexpense",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sto_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehiclerecommendation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="vehiclerecommendation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehiclerecommendation",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendations",
                to="core.visit",
            ),
        ),
        migrations.AddField(
            model_name="workpost",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_posts",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="work_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="core.workpost",
            ),
        ),
        migrations.AddIndex(
            model_name="companyoption",
            index=models.Index(
                fields=["company", "group", "is_active"],
                name="core_compan_company_3542b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyoption",
            index=models.Index(
                fields=["company", "mode", "group"],
                name="core_compan_company_7ca5ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyoption",
            index=models.Index(
                fields=["company", "semantic_role"],
                name="core_compan_company_076ddb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyoption",
            unique_together={("company", "group", "key")},
        ),
        migrations.AddIndex(
            model_name="crmclientstatus",
            index=models.Index(
                fields=["company", "phone", "plate"],
                name="core_crmcli_company_400482_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmservicereminder",
            index=models.Index(
                fields=["company", "phone", "plate", "status"],
                name="core_crmser_company_dee1eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stoexpense",
            index=models.Index(
                fields=["company", "date"], name="core_stoexp_company_e79032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stoexpense",
            index=models.Index(
                fields=["company", "category", "date"],
                name="core_stoexp_company_58a712_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workpost",
            index=models.Index(
                fields=["company", "is_active", "sort_order"],
                name="core_workpo_company_af1fc7_idx",
            ),
        ),
    ]
