# Generated by Django 5.1.2 on 2026-07-07 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_company_payment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportAccessSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("reason", models.TextField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_support_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_sessions",
                        to="core.platformclient",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeted_support_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["ended_at", "expires_at"], name="support_active_idx"
                    ),
                    models.Index(
                        fields=["admin_user", "-started_at"],
                        name="support_admin_recent_idx",
                    ),
                    models.Index(
                        fields=["platform_client", "-started_at"],
                        name="support_client_recent_idx",
                    ),
                    models.Index(
                        fields=["target_user", "-started_at"],
                        name="support_target_recent_idx",
                    ),
                ],
            },
        ),
    ]
