from django.db import migrations


TABLE_NAME = 'core_visitpayment'


def ensure_visitpayment_table(apps, schema_editor):
    connection = schema_editor.connection
    if TABLE_NAME in connection.introspection.table_names():
        return

    if connection.vendor == 'postgresql':
        schema_editor.execute(
            """
            CREATE TABLE core_visitpayment (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                amount numeric(10, 2) NOT NULL DEFAULT 0,
                payment_type varchar(30) NOT NULL DEFAULT 'cash',
                payment_purpose varchar(30) NOT NULL DEFAULT 'partial',
                comment text NULL,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                company_id bigint NOT NULL,
                visit_id bigint NOT NULL,
                created_by_id integer NULL
            )
            """
        )
    else:
        # SQLite is used by CI/local development. Keep the legacy table shape
        # compatible with the raw SQL payment service without changing existing
        # production PostgreSQL installations.
        schema_editor.execute(
            """
            CREATE TABLE core_visitpayment (
                id integer PRIMARY KEY AUTOINCREMENT,
                amount decimal(10, 2) NOT NULL DEFAULT 0,
                payment_type varchar(30) NOT NULL DEFAULT 'cash',
                payment_purpose varchar(30) NOT NULL DEFAULT 'partial',
                comment text NULL,
                created_at datetime NOT NULL,
                company_id bigint NOT NULL,
                visit_id bigint NOT NULL,
                created_by_id integer NULL
            )
            """
        )

    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS core_visitpayment_visit_idx ON core_visitpayment (visit_id, created_at)'
    )
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS core_visitpayment_company_idx ON core_visitpayment (company_id, created_at)'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_mechanic_payroll_access'),
    ]

    operations = [
        migrations.RunPython(ensure_visitpayment_table, migrations.RunPython.noop),
    ]
