from django.db import connection
from django.utils import timezone
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .partner_views import get_platform_client, is_platform_admin, is_partner_user, repair_legacy_account


def ensure_table():
    with connection.cursor() as cursor:
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS core_clientlinksettings (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title varchar(160) NOT NULL DEFAULT 'VIN-matrix підписка',
                monthly_value numeric(10, 2) NOT NULL DEFAULT 2000.00,
                public_url text NULL,
                public_note text NULL,
                instruction text NULL,
                is_active boolean NOT NULL DEFAULT true,
                updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
            );
        ''')
        cursor.execute('SELECT id FROM core_clientlinksettings ORDER BY id LIMIT 1')
        if not cursor.fetchone():
            cursor.execute(
                '''INSERT INTO core_clientlinksettings (title, monthly_value, public_url, public_note, instruction, is_active, updated_at)
                   VALUES (%s,%s,%s,%s,%s,%s,%s)''',
                ['VIN-matrix підписка', 2000, '', '', 'Вкажіть код клієнта. Наприклад: C6003', True, timezone.now()],
            )


def read_settings(admin=False, client=None):
    ensure_table()
    with connection.cursor() as cursor:
        cursor.execute('''SELECT id, title, monthly_value, public_url, public_note, instruction, is_active, updated_at FROM core_clientlinksettings ORDER BY id LIMIT 1''')
        row = cursor.fetchone()
    code = f'C{client.client_code}' if client else 'C6003'
    data = {
        'id': row[0] if row else None,
        'title': (row[1] if row else None) or 'VIN-matrix підписка',
        'monthly_value': float((row[2] if row else None) or 2000),
        'public_url': (row[3] if row else None) or '',
        'public_note': (row[4] if row else None) or '',
        'instruction': (row[5] if row else None) or 'Вкажіть код клієнта. Наприклад: C6003',
        'is_active': bool(row[6]) if row else True,
        'updated_at': row[7] if row else None,
        'client_code': code,
        'client_comment': code,
    }
    if not admin and not data['is_active']:
        data['public_url'] = ''
        data['public_note'] = ''
    return data


class ClientLinkSettingsView(APIView):
    permission_classes = [IsAuthenticated]
    def get(self, request):
        repair_legacy_account(request.user)
        return Response({'client_link_settings': read_settings(False, get_platform_client(request.user))})


class AdminClientLinkSettingsView(APIView):
    permission_classes = [IsAuthenticated]
    def get(self, request):
        repair_legacy_account(request.user)
        if not (is_platform_admin(request.user) or is_partner_user(request.user)):
            return Response({'error': 'Немає прав.'}, status=403)
        return Response({'client_link_settings': read_settings(True)})

    def patch(self, request):
        repair_legacy_account(request.user)
        if not (is_platform_admin(request.user) or is_partner_user(request.user)):
            return Response({'error': 'Немає прав.'}, status=403)
        ensure_table()
        title = str(request.data.get('title') or 'VIN-matrix підписка').strip()[:160]
        monthly_value = request.data.get('monthly_value') or 2000
        public_url = str(request.data.get('public_url') or '').strip()
        public_note = str(request.data.get('public_note') or '').strip()
        instruction = str(request.data.get('instruction') or 'Вкажіть код клієнта. Наприклад: C6003').strip()
        is_active = False if request.data.get('is_active') in [False, 'false', '0', 0] else True
        with connection.cursor() as cursor:
            cursor.execute('SELECT id FROM core_clientlinksettings ORDER BY id LIMIT 1')
            row = cursor.fetchone()
            if row:
                cursor.execute('''UPDATE core_clientlinksettings SET title=%s, monthly_value=%s, public_url=%s, public_note=%s, instruction=%s, is_active=%s, updated_at=%s, updated_by_id=%s WHERE id=%s''', [title, monthly_value, public_url, public_note, instruction, is_active, timezone.now(), request.user.id, row[0]])
            else:
                cursor.execute('''INSERT INTO core_clientlinksettings (title, monthly_value, public_url, public_note, instruction, is_active, updated_at, updated_by_id) VALUES (%s,%s,%s,%s,%s,%s,%s,%s)''', [title, monthly_value, public_url, public_note, instruction, is_active, timezone.now(), request.user.id])
        return Response({'message': 'Налаштування збережено.', 'client_link_settings': read_settings(True)})
