import json
from django.db import connection
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Visit
from .safe_crm_views import safe_ensure_company


def ensure_visit_workflow_tables():
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS core_visitacceptanceact (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id bigint NOT NULL REFERENCES core_company(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                visit_id bigint NOT NULL UNIQUE REFERENCES core_visit(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                client varchar(100) NULL,
                phone varchar(30) NULL,
                plate varchar(20) NULL,
                mileage integer NULL,
                fuel_level varchar(30) NULL,
                exterior_note text NULL,
                interior_note text NULL,
                damages text NULL,
                customer_complaint text NULL,
                note text NULL,
                status varchar(20) NOT NULL DEFAULT 'draft',
                created_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_at timestamp with time zone NOT NULL DEFAULT NOW()
            );
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS core_visitdiagnosticchecklist (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id bigint NOT NULL REFERENCES core_company(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                visit_id bigint NOT NULL UNIQUE REFERENCES core_visit(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                client varchar(100) NULL,
                phone varchar(30) NULL,
                plate varchar(20) NULL,
                checklist jsonb NOT NULL DEFAULT '{}'::jsonb,
                summary text NULL,
                status varchar(20) NOT NULL DEFAULT 'draft',
                created_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_at timestamp with time zone NOT NULL DEFAULT NOW()
            );
        """)


def row_to_dict(cursor, row):
    columns = [col[0] for col in cursor.description]
    data = dict(zip(columns, row)) if row else None
    if data and isinstance(data.get('checklist'), str):
        try:
            data['checklist'] = json.loads(data['checklist'])
        except Exception:
            data['checklist'] = {}
    return data


def get_visit_for_user(user, visit_id):
    company = safe_ensure_company(user)
    if not company or not visit_id:
        return None, company
    try:
        return Visit.objects.get(id=visit_id, company=company), company
    except Visit.DoesNotExist:
        return None, company


def to_int_or_none(value):
    try:
        return int(value) if value not in [None, ''] else None
    except (TypeError, ValueError):
        return None


class VisitAcceptanceActView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.query_params.get('visit'))
        if not visit:
            return Response({}, status=status.HTTP_200_OK)
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM core_visitacceptanceact WHERE company_id = %s AND visit_id = %s LIMIT 1", [company.id, visit.id])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data or {}, status=status.HTTP_200_OK)

    def post(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.data.get('visit'))
        if not visit:
            return Response({'detail': 'Візит не знайдено.'}, status=status.HTTP_404_NOT_FOUND)
        payload = request.data
        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO core_visitacceptanceact (
                    company_id, visit_id, client, phone, plate, mileage, fuel_level,
                    exterior_note, interior_note, damages, customer_complaint, note,
                    status, created_by_id, created_at, updated_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, NOW(), NOW())
                ON CONFLICT (visit_id) DO UPDATE SET
                    client = EXCLUDED.client,
                    phone = EXCLUDED.phone,
                    plate = EXCLUDED.plate,
                    mileage = EXCLUDED.mileage,
                    fuel_level = EXCLUDED.fuel_level,
                    exterior_note = EXCLUDED.exterior_note,
                    interior_note = EXCLUDED.interior_note,
                    damages = EXCLUDED.damages,
                    customer_complaint = EXCLUDED.customer_complaint,
                    note = EXCLUDED.note,
                    status = EXCLUDED.status,
                    updated_at = NOW()
                RETURNING *
            """, [
                company.id, visit.id, payload.get('client') or visit.client, payload.get('phone') or visit.phone,
                payload.get('plate') or visit.plate, to_int_or_none(payload.get('mileage')), payload.get('fuel_level') or '',
                payload.get('exterior_note') or '', payload.get('interior_note') or '', payload.get('damages') or '',
                payload.get('customer_complaint') or '', payload.get('note') or '', payload.get('status') or 'draft', request.user.id,
            ])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data, status=status.HTTP_200_OK)


class VisitDiagnosticChecklistView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.query_params.get('visit'))
        if not visit:
            return Response({}, status=status.HTTP_200_OK)
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM core_visitdiagnosticchecklist WHERE company_id = %s AND visit_id = %s LIMIT 1", [company.id, visit.id])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data or {}, status=status.HTTP_200_OK)

    def post(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.data.get('visit'))
        if not visit:
            return Response({'detail': 'Візит не знайдено.'}, status=status.HTTP_404_NOT_FOUND)
        payload = request.data
        checklist = payload.get('checklist') or {}
        checklist_json = checklist if isinstance(checklist, str) else json.dumps(checklist, ensure_ascii=False)
        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO core_visitdiagnosticchecklist (
                    company_id, visit_id, client, phone, plate, checklist, summary,
                    status, created_by_id, created_at, updated_at
                ) VALUES (%s, %s, %s, %s, %s, %s::jsonb, %s, %s, %s, NOW(), NOW())
                ON CONFLICT (visit_id) DO UPDATE SET
                    client = EXCLUDED.client,
                    phone = EXCLUDED.phone,
                    plate = EXCLUDED.plate,
                    checklist = EXCLUDED.checklist,
                    summary = EXCLUDED.summary,
                    status = EXCLUDED.status,
                    updated_at = NOW()
                RETURNING *
            """, [
                company.id, visit.id, payload.get('client') or visit.client, payload.get('phone') or visit.phone,
                payload.get('plate') or visit.plate, checklist_json,
                payload.get('summary') or '', payload.get('status') or 'draft', request.user.id,
            ])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data, status=status.HTTP_200_OK)
