import json
from django.db import connection, transaction
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .diagnostic_recommendations import sync_diagnostic_recommendations
from .models import CompanyOption, Visit
from .safe_crm_views import safe_ensure_company


TERMS_TEMPLATE_GROUP = 'document_template'
TERMS_TEMPLATE_KEY = 'acceptance_act_terms'


def _ensure_acceptance_terms_column():
    with connection.cursor() as cursor:
        tables = set(connection.introspection.table_names(cursor))
        if 'core_visitacceptanceact' not in tables:
            return
        columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, 'core_visitacceptanceact')
        }
        if 'terms_text' not in columns:
            cursor.execute('ALTER TABLE core_visitacceptanceact ADD COLUMN terms_text text NULL')


def _default_acceptance_terms(company):
    option = CompanyOption.objects.filter(
        company=company,
        group=TERMS_TEMPLATE_GROUP,
        key=TERMS_TEMPLATE_KEY,
        is_active=True,
    ).first()
    return str(getattr(option, 'description', '') or '').strip()


def ensure_visit_workflow_tables():
    """Create legacy workflow tables without changing production schema semantics.

    Production uses PostgreSQL/jsonb, while CI uses SQLite. These tables pre-date
    regular Django models, so their compatibility has to be handled here.
    """
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS core_visitacceptanceact (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    company_id bigint NOT NULL REFERENCES core_company(id) ON DELETE CASCADE,
                    visit_id bigint NOT NULL UNIQUE REFERENCES core_visit(id) ON DELETE CASCADE,
                    client varchar(100) NULL,
                    phone varchar(30) NULL,
                    plate varchar(20) NULL,
                    mileage integer NULL,
                    fuel_level varchar(30) NULL,
                    exterior_note text NULL,
                    interior_note text NULL,
                    damages text NULL,
                    customer_complaint text NULL,
                    note text NULL,
                    terms_text text NULL,
                    status varchar(20) NOT NULL DEFAULT 'draft',
                    created_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL,
                    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS core_visitdiagnosticchecklist (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    company_id bigint NOT NULL REFERENCES core_company(id) ON DELETE CASCADE,
                    visit_id bigint NOT NULL UNIQUE REFERENCES core_visit(id) ON DELETE CASCADE,
                    client varchar(100) NULL,
                    phone varchar(30) NULL,
                    plate varchar(20) NULL,
                    checklist text NOT NULL DEFAULT '{}',
                    summary text NULL,
                    status varchar(20) NOT NULL DEFAULT 'draft',
                    created_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL,
                    created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)
        else:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS core_visitacceptanceact (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id bigint NOT NULL REFERENCES core_company(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    visit_id bigint NOT NULL UNIQUE REFERENCES core_visit(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    client varchar(100) NULL,
                    phone varchar(30) NULL,
                    plate varchar(20) NULL,
                    mileage integer NULL,
                    fuel_level varchar(30) NULL,
                    exterior_note text NULL,
                    interior_note text NULL,
                    damages text NULL,
                    customer_complaint text NULL,
                    note text NULL,
                    terms_text text NULL,
                    status varchar(20) NOT NULL DEFAULT 'draft',
                    created_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS core_visitdiagnosticchecklist (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    company_id bigint NOT NULL REFERENCES core_company(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    visit_id bigint NOT NULL UNIQUE REFERENCES core_visit(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    client varchar(100) NULL,
                    phone varchar(30) NULL,
                    plate varchar(20) NULL,
                    checklist jsonb NOT NULL DEFAULT '{}'::jsonb,
                    summary text NULL,
                    status varchar(20) NOT NULL DEFAULT 'draft',
                    created_by_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
            """)

    # Existing production databases can already have the legacy table, so CREATE
    # TABLE IF NOT EXISTS alone is not enough when a new evidence column appears.
    _ensure_acceptance_terms_column()


def row_to_dict(cursor, row):
    columns = [col[0] for col in cursor.description]
    data = dict(zip(columns, row)) if row else None
    if data and isinstance(data.get('checklist'), str):
        try:
            data['checklist'] = json.loads(data['checklist'])
        except Exception:
            data['checklist'] = {}
    return data


def get_visit_for_user(user, visit_id):
    company = safe_ensure_company(user)
    if not company or not visit_id:
        return None, company
    try:
        return Visit.objects.get(id=visit_id, company=company), company
    except Visit.DoesNotExist:
        return None, company


def to_int_or_none(value):
    try:
        return int(value) if value not in [None, ''] else None
    except (TypeError, ValueError):
        return None


class VisitAcceptanceActView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.query_params.get('visit'))
        if not visit:
            return Response({}, status=status.HTTP_200_OK)
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM core_visitacceptanceact WHERE company_id = %s AND visit_id = %s LIMIT 1", [company.id, visit.id])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data or {}, status=status.HTTP_200_OK)

    def post(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.data.get('visit'))
        if not visit:
            return Response({'detail': 'Візит не знайдено.'}, status=status.HTTP_404_NOT_FOUND)
        payload = request.data

        # Terms are a historical snapshot. Normal draft/final saves preserve the
        # act-specific text, while a brand-new act inherits the company's current
        # template once. The dedicated owner-only endpoint can intentionally edit it.
        with connection.cursor() as cursor:
            cursor.execute(
                'SELECT terms_text FROM core_visitacceptanceact WHERE company_id = %s AND visit_id = %s LIMIT 1',
                [company.id, visit.id],
            )
            existing_terms_row = cursor.fetchone()
        if 'terms_text' in payload:
            terms_text = str(payload.get('terms_text') or '').strip()[:12000]
        elif existing_terms_row is not None:
            terms_text = existing_terms_row[0] or ''
        else:
            terms_text = _default_acceptance_terms(company)

        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO core_visitacceptanceact (
                    company_id, visit_id, client, phone, plate, mileage, fuel_level,
                    exterior_note, interior_note, damages, customer_complaint, note,
                    terms_text, status, created_by_id, created_at, updated_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                ON CONFLICT (visit_id) DO UPDATE SET
                    client = EXCLUDED.client,
                    phone = EXCLUDED.phone,
                    plate = EXCLUDED.plate,
                    mileage = EXCLUDED.mileage,
                    fuel_level = EXCLUDED.fuel_level,
                    exterior_note = EXCLUDED.exterior_note,
                    interior_note = EXCLUDED.interior_note,
                    damages = EXCLUDED.damages,
                    customer_complaint = EXCLUDED.customer_complaint,
                    note = EXCLUDED.note,
                    terms_text = EXCLUDED.terms_text,
                    status = EXCLUDED.status,
                    updated_at = CURRENT_TIMESTAMP
                RETURNING *
            """, [
                company.id, visit.id, payload.get('client') or visit.client, payload.get('phone') or visit.phone,
                payload.get('plate') or visit.plate, to_int_or_none(payload.get('mileage')), payload.get('fuel_level') or '',
                payload.get('exterior_note') or '', payload.get('interior_note') or '', payload.get('damages') or '',
                payload.get('customer_complaint') or '', payload.get('note') or '', terms_text,
                payload.get('status') or 'draft', request.user.id,
            ])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data, status=status.HTTP_200_OK)


class VisitDiagnosticChecklistView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.query_params.get('visit'))
        if not visit:
            return Response({}, status=status.HTTP_200_OK)
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM core_visitdiagnosticchecklist WHERE company_id = %s AND visit_id = %s LIMIT 1", [company.id, visit.id])
            data = row_to_dict(cursor, cursor.fetchone())
        return Response(data or {}, status=status.HTTP_200_OK)

    def post(self, request):
        ensure_visit_workflow_tables()
        visit, company = get_visit_for_user(request.user, request.data.get('visit'))
        if not visit:
            return Response({'detail': 'Візит не знайдено.'}, status=status.HTTP_404_NOT_FOUND)

        payload = request.data
        checklist = payload.get('checklist') or {}
        if isinstance(checklist, str):
            try:
                checklist = json.loads(checklist)
            except Exception:
                checklist = {}

        with transaction.atomic():
            synced_checklist, recommendation_sync = sync_diagnostic_recommendations(
                company=company,
                visit=visit,
                checklist=checklist,
                user=request.user,
            )
            checklist_json = json.dumps(synced_checklist, ensure_ascii=False)
            checklist_value_sql = '%s' if connection.vendor == 'sqlite' else '%s::jsonb'

            with connection.cursor() as cursor:
                cursor.execute(f"""
                    INSERT INTO core_visitdiagnosticchecklist (
                        company_id, visit_id, client, phone, plate, checklist, summary,
                        status, created_by_id, created_at, updated_at
                    ) VALUES (%s, %s, %s, %s, %s, {checklist_value_sql}, %s, %s, %s, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                    ON CONFLICT (visit_id) DO UPDATE SET
                        client = EXCLUDED.client,
                        phone = EXCLUDED.phone,
                        plate = EXCLUDED.plate,
                        checklist = EXCLUDED.checklist,
                        summary = EXCLUDED.summary,
                        status = EXCLUDED.status,
                        updated_at = CURRENT_TIMESTAMP
                    RETURNING *
                """, [
                    company.id, visit.id, payload.get('client') or visit.client, payload.get('phone') or visit.phone,
                    payload.get('plate') or visit.plate, checklist_json,
                    payload.get('summary') or '', payload.get('status') or 'draft', request.user.id,
                ])
                data = row_to_dict(cursor, cursor.fetchone())

        data['recommendation_sync'] = recommendation_sync
        return Response(data, status=status.HTTP_200_OK)
