from django.contrib import admin
from django.urls import path,include,re_path
from django.http import JsonResponse
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView
from rest_framework.routers import DefaultRouter
from apps.core.views import RegisterView,VisitViewSet,ServiceCatalogViewSet,ProfileSettingsView,LogoutView,ChangePasswordView
from apps.core.novapost_views import NovaPostDeliveryCreateView
