import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { normalizeVehicleMake, VEHICLE_MAKES } from '../src/utils/vehicleMakeCatalog.js';

const DATASET_KINDS = Object.freeze(['car', 'van', 'truck']);
const DEFAULT_SOURCE_COMMIT = '151f72727f2e6c5384e2122c892fb42cd58164de';
const SOURCE_MAKE_ALIASES = Object.freeze({
  'austin morris': 'Austin',
  'bmw alpina': 'Alpina',
  'caterham cars ltd': 'Caterham',
  'de lorean': 'DeLorean',
  ds: 'DS Automobiles',
  'gm daewoo': 'Daewoo',
  'iveco igloocar': 'Iveco',
  'kgm': 'SsangYong',
  'kia motors': 'Kia',
  'leyland daf': 'DAF',
  mcc: 'Smart',
  'mercedes benz mrauto': 'Mercedes-Benz',
  'micro compact car': 'Smart',
  'scania vabis': 'Scania',
  'steyr puch': 'Puch',
  volga: 'GAZ',
});

const datasetRoot = process.argv[2];
const sourceCommit = process.argv[3] || DEFAULT_SOURCE_COMMIT;

if (!datasetRoot) {
  throw new Error('Usage: node scripts/generateVehicleModelCatalog.mjs <vehiclesdb-root> [source-commit]');
}

const manifest = JSON.parse(await readFile(path.join(datasetRoot, 'manifest.json'), 'utf8'));
if (manifest.license !== 'CC-BY-4.0' || !manifest.attribution?.required) {
  throw new Error('Unexpected VehiclesDB license metadata. Review attribution before generating.');
}

const canonicalByNormalizedName = new Map(
  VEHICLE_MAKES.map((make) => [normalizeVehicleMake(make), make]),
);
const modelsByMake = new Map(VEHICLE_MAKES.map((make) => [make, new Map()]));
const matchedSourceMakes = new Set();

for (const kind of DATASET_KINDS) {
  const catalog = manifest.catalog?.[kind];
  if (!catalog?.makes || !catalog?.models) {
    throw new Error(`VehiclesDB manifest is missing the ${kind} catalog.`);
  }

  const makes = JSON.parse(await readFile(path.join(datasetRoot, catalog.makes), 'utf8'));
  const models = JSON.parse(await readFile(path.join(datasetRoot, catalog.models), 'utf8'));
  const canonicalMakeBySourceId = new Map();

  for (const sourceMake of makes) {
    const normalizedSourceMake = normalizeVehicleMake(sourceMake.name);
    const canonicalMake = SOURCE_MAKE_ALIASES[normalizedSourceMake]
      || canonicalByNormalizedName.get(normalizedSourceMake);

    if (canonicalMake) {
      canonicalMakeBySourceId.set(sourceMake.id, canonicalMake);
      matchedSourceMakes.add(`${kind}:${sourceMake.id}`);
    }
  }

  for (const sourceModel of models) {
    const canonicalMake = canonicalMakeBySourceId.get(sourceModel.make_id);
    const modelName = String(sourceModel.name || '').trim();
    const normalizedModel = normalizeVehicleMake(modelName);
    if (!canonicalMake || !normalizedModel) continue;

    const makeModels = modelsByMake.get(canonicalMake);
    if (!makeModels.has(normalizedModel)) makeModels.set(normalizedModel, modelName);
  }
}

const collator = new Intl.Collator('uk-UA', { numeric: true, sensitivity: 'base' });
const catalogEntries = VEHICLE_MAKES.map((make) => {
  const models = [...modelsByMake.get(make).values()].sort(collator.compare);
  return `  ${JSON.stringify(make)}: Object.freeze(${JSON.stringify(models)}),`;
}).join('\n');
const modelCount = [...modelsByMake.values()].reduce((total, models) => total + models.size, 0);
const populatedMakeCount = [...modelsByMake.values()].filter((models) => models.size > 0).length;

const output = `// Generated by scripts/generateVehicleModelCatalog.mjs. Do not edit manually.
// Source: VehiclesDB ${manifest.version} (${sourceCommit}), car + van + truck catalogs.
// License: CC BY 4.0. Visible attribution is rendered by VehicleModelCombobox.

import { normalizeVehicleMake } from './vehicleMakeCatalog.js';

export const VEHICLE_MODEL_CATALOG_SOURCE = Object.freeze({
  name: 'VehiclesDB',
  url: ${JSON.stringify(manifest.attribution.url)},
  version: ${JSON.stringify(manifest.version)},
  commit: ${JSON.stringify(sourceCommit)},
  license: ${JSON.stringify(manifest.license)},
});

export const VEHICLE_MODELS_BY_MAKE = Object.freeze({
${catalogEntries}
});

const MAKE_KEY_BY_NORMALIZED_NAME = new Map(
  Object.keys(VEHICLE_MODELS_BY_MAKE).map((make) => [normalizeVehicleMake(make), make]),
);

export function normalizeVehicleModel(value) {
  return normalizeVehicleMake(value);
}

export function getVehicleModels(make) {
  const canonicalMake = MAKE_KEY_BY_NORMALIZED_NAME.get(normalizeVehicleMake(make));
  return canonicalMake ? VEHICLE_MODELS_BY_MAKE[canonicalMake] : [];
}

export function hasVehicleMakeInModelCatalog(make) {
  return MAKE_KEY_BY_NORMALIZED_NAME.has(normalizeVehicleMake(make));
}

function vehicleModelScore(model, rawQuery) {
  const candidate = normalizeVehicleModel(model);
  const query = normalizeVehicleModel(rawQuery);
  if (!query) return 0;
  if (candidate === query) return 0;
  if (candidate.startsWith(query)) return 1;
  if (candidate.split(' ').some((word) => word.startsWith(query))) return 2;
  if (candidate.includes(query)) return 3;
  return Number.POSITIVE_INFINITY;
}

export function searchVehicleModels(models, query) {
  const safeModels = Array.isArray(models) ? models : [];
  if (!normalizeVehicleModel(query)) return safeModels;

  return safeModels
    .map((model, index) => ({ model, index, score: vehicleModelScore(model, query) }))
    .filter((result) => Number.isFinite(result.score))
    .sort((left, right) => left.score - right.score || left.index - right.index)
    .map((result) => result.model);
}

export function vehicleModelAfterMakeChange(previousMake, nextMake, currentModel) {
  return normalizeVehicleMake(previousMake) === normalizeVehicleMake(nextMake)
    ? currentModel
    : '';
}
`;

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(scriptDirectory, '../src/utils/vehicleModelCatalog.js');
await writeFile(outputPath, output, 'utf8');

console.log(`Generated ${modelCount} models for ${populatedMakeCount}/${VEHICLE_MAKES.length} makes from ${matchedSourceMakes.size} source make catalogs.`);
