import React, { useEffect, useMemo, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock, Copy, CreditCard, Edit3, PackageCheck, Plus, Printer, RotateCcw, Search, Send, ShoppingCart, Trash2, Truck, UserRound, Wrench, X, XCircle } from 'lucide-react';
import api from '../api/axios';

const emptyOrder = { client: '', phone: '', plate: '', vin_code: '', source: 'Телефон', delivery_type: 'pickup', payment_status: 'unpaid', comment: '' };
const emptyPart = { name: '', brand: '', article: '', supplier: '', buy_price: '', sell_price: '', quantity: 1, status: 'WAITING' };
const emptyQuick = { name: '', brand: '', article: '', supplier: 'Склад / магазин', buy_price: '', sell_price: '', quantity: 1, payment_status: 'paid', comment: '' };
const field = 'w-full bg-slate-50 border-2 border-slate-200 rounded-xl px-4 py-3 text-sm font-bold outline-none focus:bg-white focus:border-blue-500';
const arr = (v) => Array.isArray(v) ? v : [];
const num = (v) => Number(String(v || 0).replace(',', '.')) || 0;
const money = (v) => `${Number(v || 0).toLocaleString('uk-UA', { maximumFractionDigits: 2 })} ₴`;
const dateISO = (d = new Date()) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
const shiftDate = (v, days) => { const d = new Date(`${v}T12:00:00`); d.setDate(d.getDate() + days); return dateISO(d); };
const orderDate = (o) => dateISO(new Date(o?.scheduled_datetime || o?.created_at || Date.now()));
const parseDelivery = (o) => { try { const raw = o?.delivery_data; if (!raw) return {}; return typeof raw === 'string' && raw.trim().startsWith('{') ? JSON.parse(raw) : (typeof raw === 'object' ? raw : {}); } catch { return {}; } };
const labels = { SELECTION: 'В обробці', PENDING: 'В обробці', DRAFT: 'В обробці', ORDERED: 'Очікує товар', IN_PROGRESS: 'Очікує товар', DONE: 'Готове', SHIPPED: 'Відправлено', COMPLETED: 'Виконано', CANCELLED: 'Скасовано' };
const pay = { unpaid: 'Не оплачено', prepaid: 'Передплата', paid: 'Оплачено', cod: 'Післяплата', debt: 'Борг' };
const returnReasons = ['Не підійшло', 'Брак', 'Клієнт відмовився', 'Помилка продавця', 'Помилка постачальника', 'Повернення Новою поштою', 'Інше'];
const cancelReasons = ['Клієнт передумав', 'Дорого', 'Не підійшло', 'Немає в наявності', 'Довга доставка', 'Знайшов дешевше', 'Дубль замовлення', 'Інше'];
const columns = [
  { title: 'В обробці', key: 'processing', icon: Clock, style: 'border-amber-200 bg-amber-50/70 text-amber-700', match: (o) => ['SELECTION', 'PENDING', 'DRAFT'].includes(o.status) },
  { title: 'Очікує товар', key: 'waiting', icon: Truck, style: 'border-blue-200 bg-blue-50/70 text-blue-700', match: (o) => ['ORDERED', 'IN_PROGRESS'].includes(o.status) },
  { title: 'Готове', key: 'ready', icon: CheckCircle2, style: 'border-indigo-200 bg-indigo-50/70 text-indigo-700', match: (o) => o.status === 'DONE' },
  { title: 'Відправлено', key: 'shipped', icon: Send, style: 'border-emerald-200 bg-emerald-50/70 text-emerald-700', match: (o) => ['SHIPPED', 'COMPLETED'].includes(o.status) },
];

function calc(p) { const q = num(p.quantity) || 1, buy = num(p.buy_price), sell = num(p.sell_price), revenue = q * sell, cost = q * buy, profit = revenue - cost; return { q, buy, sell, revenue, cost, profit, margin: revenue ? profit / revenue * 100 : 0 }; }
function totals(o) { const t = arr(o?.parts).reduce((a, p) => { const c = calc(p); a.revenue += c.revenue; a.cost += c.cost; a.profit += c.profit; return a; }, { revenue: 0, cost: 0, profit: 0 }); t.count = arr(o?.parts).length; t.margin = t.revenue ? t.profit / t.revenue * 100 : 0; return t; }
function sourceLabel(p) { return p?.source_label || p?.supplier || (p?.inventory_item ? 'Мій склад' : 'Постачальник не вказаний'); }
function stockLabel(p) { return p?.stock_status === 'sold' ? 'Склад: списано' : p?.stock_status === 'reserved' ? 'Склад: резерв' : p?.stock_status === 'returned' ? 'Склад: повернено' : p?.stock_status === 'defective' ? 'Брак / не на складі' : p?.stock_status === 'released' ? 'Склад: резерв знято' : p?.inventory_item ? 'Склад: знайдено' : 'Склад: не знайдено'; }
function smartStatus(order, patch = null) { const d = { ...parseDelivery(order), ...(patch || {}) }, parts = arr(order.parts); if (d.delivery_status === 'sent') return 'SHIPPED'; if (!parts.length) return 'SELECTION'; if (parts.some((p) => ['WAITING', 'IN_TRANSIT'].includes(p.status || 'WAITING'))) return 'ORDERED'; if (parts.every((p) => ['ARRIVED', 'UNAVAILABLE'].includes(p.status || 'WAITING'))) return 'DONE'; return order.status || 'SELECTION'; }
function hint(order) { const d = parseDelivery(order), parts = arr(order.parts); if (d.delivery_status === 'sent') return 'Замовлення відправлено. Після отримання/оплати можна закрити.'; if (!parts.length) return 'Додайте товари — замовлення залишиться в обробці.'; if (parts.some((p) => ['WAITING', 'IN_TRANSIT'].includes(p.status || 'WAITING'))) return 'Є товари в очікуванні — статус: Очікує товар.'; return 'Усі товари отримано — статус: Готове.'; }

export default function StoreOrdersModernPrepay() {
  const location = useLocation();
  const [orders, setOrders] = useState([]), [loading, setLoading] = useState(true), [message, setMessage] = useState(''), [search, setSearch] = useState(''), [day, setDay] = useState(dateISO()), [selected, setSelected] = useState(null), [modal, setModal] = useState(null), [tab, setTab] = useState('client'), [partModal, setPartModal] = useState(null), [busy, setBusy] = useState(false);
  const [orderForm, setOrderForm] = useState({ ...emptyOrder }), [partForm, setPartForm] = useState({ ...emptyPart }), [quick, setQuick] = useState({ ...emptyQuick });

  const load = async () => { setLoading(true); try { const r = await api.get(`/api/visits/?date=${day}`); setOrders(Array.isArray(r.data) ? r.data : []); } catch { setMessage('Не вдалося завантажити замовлення.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [day]);

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const visitId = params.get('visit_id');
    if (!visitId) return;
    let cancelled = false;
    const openDeepLink = async () => {
      setLoading(true);
      try {
        const r = await api.get(`/api/visits/${visitId}/`);
        if (cancelled) return;
        const order = r.data;
        const targetDay = orderDate(order);
        setSelected(order);
        setTab(params.get('tab') || 'parts');
        setSearch(String(order.id));
        setOrders((prev) => prev.some((x) => Number(x.id) === Number(order.id)) ? prev.map((x) => Number(x.id) === Number(order.id) ? order : x) : [order, ...prev]);
        if (targetDay && targetDay !== day) setDay(targetDay);
      } catch {
        if (!cancelled) setMessage('Не вдалося відкрити замовлення з повідомлення.');
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    openDeepLink();
    return () => { cancelled = true; };
  }, [location.search]);

  const setFresh = (o) => { setSelected(o); setOrders((p) => p.some((x) => x.id === o.id) ? p.map((x) => x.id === o.id ? o : x) : [o, ...p]); return o; };
  const refresh = async (id = selected?.id) => { if (!id) return null; try { const r = await api.get(`/api/visits/${id}/`); return setFresh(r.data); } catch { load(); return null; } };
  const patchOrder = async (payload, id = selected?.id) => { if (!id) return null; setBusy(true); try { const r = await api.patch(`/api/visits/${id}/`, payload); return setFresh(r.data); } catch { setMessage('Не вдалося оновити замовлення.'); return null; } finally { setBusy(false); } };

  const filtered = useMemo(() => { const q = search.toLowerCase().trim().replace('№', ''); return orders.filter((o) => { const d = parseDelivery(o); const text = [o.id, o.client, o.phone, o.plate, o.vin_code, d.ttn, ...arr(o.parts).flatMap((p) => [p.brand, p.article, p.name, p.supplier, p.source_label])].filter(Boolean).join(' ').toLowerCase(); return !q || text.includes(q); }); }, [orders, search]);
  const groups = useMemo(() => columns.map((c) => ({ ...c, orders: filtered.filter(c.match) })), [filtered]);

  const createOrder = async (e) => { e.preventDefault(); setBusy(true); try { const delivery = { source: orderForm.source, delivery_status: 'draft', mode: 'store' }; const r = await api.post('/api/visits/', { client: orderForm.client.trim(), phone: orderForm.phone.trim() || '0000000000', plate: (orderForm.plate || `ORDER-${Date.now()}`).trim().toUpperCase(), vin_code: orderForm.vin_code.trim().toUpperCase() || null, status: 'SELECTION', delivery_type: orderForm.delivery_type, delivery_data: JSON.stringify(delivery), payment_status: orderForm.payment_status, prepayment_amount: 0, comment: orderForm.comment, scheduled_datetime: new Date(`${day}T12:00:00`).toISOString() }); setFresh(r.data); setModal(null); setTab('parts'); } catch (e2) { setMessage(e2.response?.data?.error || 'Не вдалося створити замовлення.'); } finally { setBusy(false); } };
  const addPart = async (e) => { e.preventDefault(); if (!selected?.id) return; setBusy(true); try { await api.post('/api/order-parts/', { visit: selected.id, name: partForm.name.trim(), brand: (partForm.brand || 'Без бренду').trim(), article: (partForm.article || 'manual').trim(), supplier: (partForm.supplier || 'Ручне додавання').trim(), buy_price: num(partForm.buy_price), sell_price: num(partForm.sell_price), quantity: num(partForm.quantity) || 1, status: partForm.status || 'WAITING' }); setPartForm({ ...emptyPart }); const fresh = await refresh(); if (fresh) await patchOrder({ status: smartStatus(fresh) }, fresh.id); setMessage('Товар додано.'); } catch { setMessage('Не вдалося додати товар.'); } finally { setBusy(false); } };
  const updatePartStatus = async (part, status) => { setBusy(true); try { await api.patch(`/api/order-parts/${part.id}/`, { status }); const fresh = await refresh(); if (fresh) await patchOrder({ status: smartStatus(fresh) }, fresh.id); } catch { setMessage('Не вдалося змінити статус товару.'); } finally { setBusy(false); } };
  const updateDelivery = async (patch) => { const delivery = { ...parseDelivery(selected), ...patch, mode: 'store' }; await patchOrder({ delivery_data: JSON.stringify(delivery), status: smartStatus(selected, patch) }); };
  const editPart = async (data) => { if (!partModal?.id) return; setBusy(true); try { await api.patch(`/api/order-parts/${partModal.id}/`, data); setModal(null); setPartModal(null); const fresh = await refresh(); if (fresh) await patchOrder({ status: smartStatus(fresh) }, fresh.id); setMessage('Товар оновлено.'); } catch { setMessage('Не вдалося редагувати товар.'); } finally { setBusy(false); } };
  const returnPart = async (payload) => { if (!partModal?.id) return; setBusy(true); try { const r = await api.post(`/api/order-parts/${partModal.id}/return/`, payload); setMessage(r.data?.message || 'Повернення виконано.'); setModal(null); setPartModal(null); await refresh(); } catch (e) { setMessage(e.response?.data?.message || 'Не вдалося оформити повернення.'); } finally { setBusy(false); } };
  const deletePart = async (payload) => { if (!partModal?.id) return; setBusy(true); try { const r = await api.post(`/api/order-parts/${partModal.id}/delete-with-stock/`, payload); const fresh = r.data?.visit ? setFresh(r.data.visit) : await refresh(); if (fresh) await patchOrder({ status: smartStatus(fresh) }, fresh.id); setMessage(r.data?.message || 'Товар видалено.'); setModal(null); setPartModal(null); } catch (e) { setMessage(e.response?.data?.message || 'Не вдалося видалити товар.'); } finally { setBusy(false); } };
  const cancelOrder = async ({ reason, comment }) => { await patchOrder({ status: 'CANCELLED', delivery_data: JSON.stringify({ ...parseDelivery(selected), cancel_reason: reason, cancel_comment: comment, cancelled_at: new Date().toISOString(), mode: 'store' }) }); setModal(null); };
  const copyTtn = async () => { const ttn = parseDelivery(selected).ttn; if (ttn) { await navigator.clipboard.writeText(ttn); setMessage('ТТН скопійовано.'); } };
  const markPaid = async (total) => { await patchOrder({ payment_status: 'paid', prepayment_amount: total }); setMessage('Замовлення оплачено повністю.'); };
  const savePrepay = async (amount) => { await patchOrder({ payment_status: num(amount) > 0 ? 'prepaid' : 'unpaid', prepayment_amount: num(amount) }); setMessage('Передплату збережено.'); };
  const printReceipt = (order) => { const parts = arr(order.parts), t = totals(order), w = window.open('', '_blank'); if (!w) return; w.document.write(`<html><head><meta charset="utf-8"><title>Чек №${order.id}</title><style>body{font-family:Arial;margin:32px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:8px}.right{text-align:right}</style></head><body onload="window.print()"><h1>Товарний чек №${order.id}</h1><p>${order.client || ''} ${order.phone || ''}</p><table><tr><th>Бренд</th><th>Артикул</th><th>Назва</th><th>К-сть</th><th>Ціна</th><th>Сума</th></tr>${parts.map((p) => { const c = calc(p); return `<tr><td>${p.brand || ''}</td><td>${p.article || ''}</td><td>${p.name || ''}</td><td>${c.q}</td><td>${money(c.sell)}</td><td>${money(c.revenue)}</td></tr>`; }).join('')}</table><h2 class="right">Разом: ${money(t.revenue)}</h2></body></html>`); w.document.close(); };
  const quickSale = async (e) => { e.preventDefault(); setBusy(true); try { const order = await api.post('/api/visits/', { client: 'Роздрібний покупець', phone: '0000000000', plate: `SALE-${Date.now()}`.slice(0, 20), vin_code: null, status: 'COMPLETED', delivery_type: 'pickup', delivery_data: JSON.stringify({ source: 'Швидкий продаж', mode: 'store', quick_sale: true, delivery_status: 'received' }), payment_status: quick.payment_status, prepayment_amount: 0, comment: quick.comment || 'Швидкий продаж', scheduled_datetime: new Date(`${day}T12:00:00`).toISOString() }); const part = await api.post('/api/order-parts/', { visit: order.data.id, name: quick.name.trim(), brand: (quick.brand || 'Без бренду').trim(), article: (quick.article || 'manual').trim(), supplier: (quick.supplier || 'Швидкий продаж').trim(), buy_price: num(quick.buy_price), sell_price: num(quick.sell_price), quantity: num(quick.quantity) || 1, status: 'ARRIVED' }); const completed = { ...order.data, parts: [part.data] }; setFresh(completed); setModal(null); setQuick({ ...emptyQuick }); setTimeout(() => printReceipt(completed), 250); } catch { setMessage('Не вдалося створити швидкий продаж.'); } finally { setBusy(false); } };

  return <div className="max-w-[1600px] mx-auto p-3 md:p-8 md:pl-72 min-h-screen pb-24"><Header setModal={setModal} setOrderForm={setOrderForm} setQuick={setQuick} />{message && <Notice message={message} onClose={() => setMessage('')} />}<SearchDate search={search} setSearch={setSearch} day={day} setDay={setDay} count={filtered.length} />{loading ? <Empty text="Завантаження..." /> : <div className="grid grid-cols-1 xl:grid-cols-4 gap-4">{groups.map((c) => <Column key={c.key} c={c} onOpen={(o) => { setSelected(o); setTab('client'); }} />)}</div>}{selected && <Drawer order={selected} tab={tab} setTab={setTab} setOrder={setSelected} onPatch={patchOrder} onPay={markPaid} onPrepay={savePrepay} onUpdateDelivery={updateDelivery} onCancel={() => setModal('cancel')} partForm={partForm} setPartForm={setPartForm} onAddPart={addPart} onPartStatus={updatePartStatus} onEdit={(p) => { setPartModal(p); setModal('editPart'); }} onReturn={(p) => { setPartModal(p); setModal('returnPart'); }} onDelete={(p) => { setPartModal(p); setModal('deletePart'); }} onPrint={printReceipt} onCopyTtn={copyTtn} />}{modal === 'order' && <Modal title="Нове замовлення" onClose={() => setModal(null)}><OrderForm form={orderForm} setForm={setOrderForm} onSubmit={createOrder} busy={busy} /></Modal>}{modal === 'quick' && <Modal title="Швидкий продаж" onClose={() => setModal(null)}><QuickForm form={quick} setForm={setQuick} onSubmit={quickSale} busy={busy} /></Modal>}{modal === 'cancel' && selected && <CancelModal onClose={() => setModal(null)} onSubmit={cancelOrder} busy={busy} />}{modal === 'returnPart' && partModal && <ReturnModal part={partModal} onClose={() => setModal(null)} onSubmit={returnPart} busy={busy} />}{modal === 'deletePart' && partModal && <DeleteModal part={partModal} onClose={() => setModal(null)} onSubmit={deletePart} busy={busy} />}{modal === 'editPart' && partModal && <EditPartModal part={partModal} onClose={() => setModal(null)} onSubmit={editPart} busy={busy} />}</div>;
}

function Header({ setModal, setOrderForm, setQuick }) { return <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 mb-5"><div><h1 className="text-2xl md:text-3xl font-black uppercase italic flex items-center gap-2"><PackageCheck className="text-blue-600" /> Дошка замовлень</h1><p className="text-slate-500 font-semibold text-sm mt-1">Магазин автозапчастин: замовлення, склад, доставка, чек.</p></div><div className="flex flex-col sm:flex-row gap-2"><button onClick={() => { setQuick({ ...emptyQuick }); setModal('quick'); }} className="btn-green"><ShoppingCart size={16} /> Швидкий продаж</button><button onClick={() => { setOrderForm({ ...emptyOrder }); setModal('order'); }} className="btn-blue"><Plus size={16} /> Нове замовлення</button></div></div>; }
function SearchDate({ search, setSearch, day, setDay, count }) { return <div className="bg-white border rounded-3xl shadow-sm p-3 sm:p-4 mb-5 grid grid-cols-1 xl:grid-cols-[1fr_auto] gap-3"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Пошук по №, клієнту, телефону, ТТН, артикулу..." className={field.replace('px-4', 'pl-9 pr-4')} /></div><div className="flex items-center gap-2 bg-slate-50 border rounded-xl px-2 py-2"><button onClick={() => setDay(shiftDate(day, -1))} className="navbtn"><ChevronLeft size={16} /></button><button onClick={() => setDay(dateISO())} className="px-3 py-2 bg-white border rounded-lg font-black text-xs uppercase flex items-center gap-2 min-w-[190px] justify-center"><CalendarDays size={15} />{new Date(`${day}T12:00:00`).toLocaleDateString('uk-UA', { weekday: 'short', day: '2-digit', month: 'long' })} • {count}</button><button onClick={() => setDay(shiftDate(day, 1))} className="navbtn"><ChevronRight size={16} /></button></div></div>; }
function Column({ c, onOpen }) { const Icon = c.icon; return <div className={`rounded-3xl border shadow-sm p-4 min-h-[280px] ${c.style}`}><h3 className="font-black uppercase text-sm flex items-center gap-2 mb-4"><span className="w-9 h-9 rounded-2xl flex items-center justify-center bg-white/80"><Icon size={18} /></span>{c.title}<span className="ml-auto bg-white/80 px-3 py-1 rounded-xl text-slate-700">{c.orders.length}</span></h3><div className="space-y-3">{c.orders.map((o) => <Card key={o.id} order={o} onOpen={() => onOpen(o)} />)}{!c.orders.length && <Empty text="Пусто" />}</div></div>; }
function Card({ order, onOpen }) { const t = totals(order), paid = num(order.prepayment_amount), left = Math.max(t.revenue - paid, 0); return <button onClick={onOpen} className="w-full text-left bg-white/90 hover:bg-white border border-white/80 hover:border-blue-200 rounded-2xl p-4 shadow-sm"><p className="font-black text-slate-900">№{order.id} • {order.client || 'Покупець'}</p><p className="text-xs font-bold text-slate-500 mt-1">{order.phone || '-'} • {order.plate || 'Без авто'}</p><div className="mt-3 flex flex-wrap gap-2"><Badge>{t.count} поз.</Badge><Badge>{money(t.revenue)}</Badge><Badge>{labels[order.status] || order.status}</Badge><Badge>{pay[order.payment_status] || 'Оплата'}</Badge>{left > 0 && order.payment_status !== 'paid' ? <Badge>Залишок {money(left)}</Badge> : null}</div></button>; }
function Drawer(p) { const { order, tab, setTab, setOrder, onPatch, onPay, onPrepay, onUpdateDelivery, onCancel, partForm, setPartForm, onAddPart, onPartStatus, onEdit, onReturn, onDelete, onPrint, onCopyTtn } = p; const d = parseDelivery(order), t = totals(order); return <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex justify-end"><div className="bg-white w-full max-w-5xl h-full overflow-y-auto shadow-2xl p-4 md:p-7"><div className="flex items-start justify-between gap-3 mb-4"><div><h2 className="text-2xl font-black uppercase">Замовлення №{order.id}</h2><p className="text-sm font-bold text-slate-500">{order.client} • {order.phone}</p></div><div className="flex items-center gap-2"><Mac title="Чек" onClick={() => onPrint(order)} icon={<Printer size={15} />} /><Mac danger title="Скасувати" onClick={onCancel} icon={<XCircle size={15} />} /><Mac ok title="Закрити" onClick={() => onPatch({ status: 'COMPLETED' })} icon={<CheckCircle2 size={15} />} /><button onClick={() => setOrder(null)} className="p-2 bg-slate-100 rounded-xl"><X size={18} /></button></div></div><Summary order={order} totals={t} /><PaymentBar order={order} totals={t} onPay={onPay} onPrepay={onPrepay} /><div className="bg-slate-50 border rounded-2xl p-3 mb-4 text-sm font-bold text-slate-600">💡 {hint(order)}</div><Tabs active={tab} setActive={setTab} />{tab === 'client' && <Panel title="Покупець"><Info label="Клієнт" value={order.client} /><Info label="Телефон" value={order.phone} /><Info label="Авто / VIN" value={`${order.plate || '-'} ${order.vin_code || ''}`} /><Info label="Джерело" value={d.source || '-'} /></Panel>}{tab === 'parts' && <PartsPanel parts={arr(order.parts)} partForm={partForm} setPartForm={setPartForm} onAddPart={onAddPart} onPartStatus={onPartStatus} onEdit={onEdit} onReturn={onReturn} onDelete={onDelete} />}{tab === 'delivery' && <DeliveryPanel order={order} delivery={d} onPatch={onPatch} onUpdateDelivery={onUpdateDelivery} onCopyTtn={onCopyTtn} />}</div></div>; }
function PaymentBar({ order, totals, onPay, onPrepay }) { const paidStatus = order.payment_status === 'paid', paid = paidStatus ? totals.revenue : num(order.prepayment_amount), left = Math.max(totals.revenue - paid, 0); const [draft, setDraft] = useState(String(paid || '')); useEffect(() => setDraft(String(paid || '')), [order.id, order.prepayment_amount, totals.revenue, paidStatus]); return <div className={`mb-4 rounded-2xl border p-3 md:p-4 ${paidStatus ? 'bg-emerald-50 border-emerald-100' : 'bg-amber-50 border-amber-100'}`}><div className="flex flex-col xl:flex-row xl:items-center justify-between gap-4"><div className="flex items-center gap-3"><span className={`w-10 h-10 rounded-2xl flex items-center justify-center ${paidStatus ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}><CreditCard size={19} /></span><div><p className="text-[10px] font-black uppercase text-slate-400">Оплата</p><p className={`font-black ${paidStatus ? 'text-emerald-700' : 'text-amber-800'}`}>{pay[order.payment_status] || 'Не оплачено'}</p></div></div><div className="grid grid-cols-3 gap-2 flex-1"><PayMini label="Сума" value={money(totals.revenue)} /><PayMini label="Внесено" value={money(paid)} /><PayMini label="Залишилось" value={money(left)} bad={left > 0 && !paidStatus} good={left <= 0} /></div></div>{!paidStatus && <div className="grid grid-cols-1 md:grid-cols-[1fr_auto_auto] gap-2 mt-3"><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Сума передплати" className={field} /><button onClick={() => onPrepay(draft)} className="bg-blue-600 text-white rounded-xl px-5 py-3 text-xs font-black uppercase">Зберегти передплату</button><button onClick={() => onPay(totals.revenue)} className="bg-emerald-600 text-white rounded-xl px-5 py-3 text-xs font-black uppercase">Оплачено повністю</button></div>}</div>; }
function Tabs({ active, setActive }) { const tabs = [['client', UserRound, 'Клієнт'], ['parts', Wrench, 'Запчастини'], ['delivery', Truck, 'Доставка']]; return <div className="bg-slate-100 rounded-2xl p-1 grid grid-cols-3 gap-1 mb-4 sticky top-0 z-10">{tabs.map(([k, Icon, l]) => <button key={k} onClick={() => setActive(k)} className={`rounded-xl p-3 font-black uppercase text-xs flex items-center justify-center gap-2 ${active === k ? 'bg-blue-600 text-white' : 'text-slate-500 hover:bg-white'}`}><Icon size={15} />{l}</button>)}</div>; }
function Summary({ order, totals }) { const paid = order.payment_status === 'paid' ? totals.revenue : num(order.prepayment_amount), left = Math.max(totals.revenue - paid, 0); return <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-3 mb-4"><Metric label="Статус" value={labels[order.status] || order.status || '-'} /><Metric label="Оплата" value={pay[order.payment_status] || '-'} /><Metric label="Залишок" value={money(left)} positive={left <= 0} /><Metric label="Позицій" value={totals.count} /><Metric label="Продаж" value={money(totals.revenue)} /><Metric label="Прибуток" value={money(totals.profit)} positive={totals.profit >= 0} /><Metric label="Маржа" value={`${totals.margin.toFixed(1)}%`} positive={totals.profit >= 0} /></div>; }
function PartsPanel({ parts, partForm, setPartForm, onAddPart, onPartStatus, onEdit, onReturn, onDelete }) { return <Panel title="Товари та прибуток"><form onSubmit={onAddPart} className="grid grid-cols-1 md:grid-cols-4 gap-2 mb-4"><F required placeholder="Назва" value={partForm.name} onChange={(v) => setPartForm({ ...partForm, name: v })} /><F placeholder="Бренд" value={partForm.brand} onChange={(v) => setPartForm({ ...partForm, brand: v })} /><F placeholder="Артикул" value={partForm.article} onChange={(v) => setPartForm({ ...partForm, article: v })} /><F placeholder="Постачальник" value={partForm.supplier} onChange={(v) => setPartForm({ ...partForm, supplier: v })} /><F placeholder="Закупка" value={partForm.buy_price} onChange={(v) => setPartForm({ ...partForm, buy_price: v })} /><F required placeholder="Продаж" value={partForm.sell_price} onChange={(v) => setPartForm({ ...partForm, sell_price: v })} /><F placeholder="К-сть" value={partForm.quantity} onChange={(v) => setPartForm({ ...partForm, quantity: v })} /><button className="btn-blue">Додати</button></form><div className="space-y-2">{parts.map((p) => <Part key={p.id} part={p} onStatus={onPartStatus} onEdit={onEdit} onReturn={onReturn} onDelete={onDelete} />)}{!parts.length && <Empty text="Товари ще не додані" />}</div></Panel>; }
function Part({ part, onStatus, onEdit, onReturn, onDelete }) { const c = calc(part); return <div className="bg-slate-50 border rounded-2xl p-3"><div className="flex flex-col xl:flex-row xl:items-center gap-3"><div className="flex-1"><p className="font-black">{part.brand} {part.article}</p><p className="text-sm font-bold text-slate-500">{part.name} • {c.q} шт</p><div className="flex flex-wrap gap-2 mt-2"><Badge>{sourceLabel(part)}</Badge><Badge>{stockLabel(part)}</Badge></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-2 text-[11px] font-black"><span>Закупка: {money(c.cost)}</span><span>Продаж: {money(c.revenue)}</span><span className="text-emerald-600">Прибуток: {money(c.profit)}</span><span className="text-emerald-600">Маржа: {c.margin.toFixed(1)}%</span></div></div><select value={part.status || 'WAITING'} onChange={(e) => onStatus(part, e.target.value)} className={`${field} xl:w-44`}><option value="WAITING">До замовлення</option><option value="IN_TRANSIT">В дорозі</option><option value="ARRIVED">Отримано</option><option value="UNAVAILABLE">Відмова</option></select><div className="flex xl:flex-col gap-2"><IconBtn title="Редагувати" onClick={() => onEdit(part)} icon={<Edit3 size={15} />} /><IconBtn title="Повернення" onClick={() => onReturn(part)} icon={<RotateCcw size={15} />} /><IconBtn danger title="Видалити" onClick={() => onDelete(part)} icon={<Trash2 size={15} />} /></div></div></div>; }
function DeliveryPanel({ order, delivery, onPatch, onUpdateDelivery, onCopyTtn }) { return <Panel title="Нова пошта / доставка"><Sel label="Оплата" value={order.payment_status || 'unpaid'} onChange={(v) => onPatch({ payment_status: v })} options={[['unpaid', 'Не оплачено'], ['prepaid', 'Передплата'], ['paid', 'Оплачено'], ['cod', 'Післяплата'], ['debt', 'Борг']]} /><Sel label="Доставка" value={order.delivery_type || 'pickup'} onChange={(v) => onPatch({ delivery_type: v })} options={[['pickup', 'Самовивіз'], ['nova_poshta', 'Нова пошта'], ['courier', 'Курʼєр']]} /><div className="grid grid-cols-1 md:grid-cols-2 gap-2"><Labeled label="Місто" value={delivery.city || ''} onBlur={(v) => onUpdateDelivery({ city: v })} /><Labeled label="Відділення / адреса" value={delivery.warehouse || ''} onBlur={(v) => onUpdateDelivery({ warehouse: v })} /><Labeled label="Отримувач" value={delivery.recipient || ''} onBlur={(v) => onUpdateDelivery({ recipient: v })} /><Labeled label="Телефон отримувача" value={delivery.recipient_phone || ''} onBlur={(v) => onUpdateDelivery({ recipient_phone: v })} /><div className="flex gap-2 items-end"><div className="flex-1"><Labeled label="ТТН" value={delivery.ttn || ''} onBlur={(v) => onUpdateDelivery({ ttn: v })} /></div><button type="button" onClick={onCopyTtn} disabled={!delivery.ttn} className="mb-2 bg-blue-50 text-blue-700 border border-blue-100 rounded-xl p-3 disabled:opacity-40"><Copy size={18} /></button></div><Sel label="Статус доставки" value={delivery.delivery_status || 'draft'} onChange={(v) => onUpdateDelivery({ delivery_status: v })} options={[['draft', 'Не відправлено'], ['sent', 'Відправлено'], ['received', 'Отримано'], ['returned', 'Повернення']]} /><Labeled label="Вартість доставки" value={delivery.delivery_cost || ''} onBlur={(v) => onUpdateDelivery({ delivery_cost: v })} /><Labeled label="Післяплата" value={delivery.cod_amount || ''} onBlur={(v) => onUpdateDelivery({ cod_amount: v })} /><Labeled label="Комісія післяплати" value={delivery.cod_commission || ''} onBlur={(v) => onUpdateDelivery({ cod_commission: v })} /></div></Panel>; }
function ReturnModal({ part, onClose, onSubmit, busy }) { const [reason, setReason] = useState(returnReasons[0]), [quantity, setQuantity] = useState(part.quantity || 1), [returnToStock, setReturnToStock] = useState(true), [comment, setComment] = useState(''); return <Modal title="Повернення товару" onClose={onClose} top><div className="space-y-3"><p className="font-black">{part.brand} {part.article} — {part.name}</p><Sel label="Причина" value={reason} onChange={setReason} options={returnReasons.map((r) => [r, r])} /><Input label="Кількість" value={quantity} onChange={setQuantity} /><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={returnToStock} onChange={(e) => setReturnToStock(e.target.checked)} /> Повернути на склад</label><textarea className={`${field} min-h-[90px]`} value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Коментар" /><button disabled={busy} onClick={() => onSubmit({ reason, quantity, comment, return_to_stock: returnToStock })} className="btn-blue w-full">Оформити повернення</button></div></Modal>; }
function DeleteModal({ part, onClose, onSubmit, busy }) { const [stockAction, setStockAction] = useState(part.stock_status === 'sold' ? 'return' : 'release'); return <Modal title="Видалити товар" onClose={onClose} top><div className="space-y-3"><p className="font-black">{part.brand} {part.article} — {part.name}</p><Sel label="Дія зі складом" value={stockAction} onChange={setStockAction} options={[['return', 'Повернути на склад'], ['release', 'Зняти резерв'], ['none', 'Просто видалити']]} /><button disabled={busy} onClick={() => onSubmit({ stock_action: stockAction })} className="bg-rose-600 text-white rounded-xl px-5 py-3 text-xs font-black uppercase w-full">Видалити</button></div></Modal>; }
function EditPartModal({ part, onClose, onSubmit, busy }) { const [form, setForm] = useState({ name: part.name || '', brand: part.brand || '', article: part.article || '', supplier: part.supplier || '', buy_price: part.buy_price || '', sell_price: part.sell_price || '', quantity: part.quantity || 1, status: part.status || 'WAITING' }); return <Modal title="Редагувати товар" onClose={onClose} top><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Input label="Назва" value={form.name} onChange={(v) => setForm({ ...form, name: v })} /><Input label="Бренд" value={form.brand} onChange={(v) => setForm({ ...form, brand: v })} /><Input label="Артикул" value={form.article} onChange={(v) => setForm({ ...form, article: v })} /><Input label="Постачальник" value={form.supplier} onChange={(v) => setForm({ ...form, supplier: v })} /><Input label="Закупка" value={form.buy_price} onChange={(v) => setForm({ ...form, buy_price: v })} /><Input label="Продаж" value={form.sell_price} onChange={(v) => setForm({ ...form, sell_price: v })} /><Input label="Кількість" value={form.quantity} onChange={(v) => setForm({ ...form, quantity: v })} /><Sel label="Статус" value={form.status} onChange={(v) => setForm({ ...form, status: v })} options={[['WAITING', 'До замовлення'], ['IN_TRANSIT', 'В дорозі'], ['ARRIVED', 'Отримано'], ['UNAVAILABLE', 'Відмова']]} /></div><button disabled={busy} onClick={() => onSubmit(form)} className="btn-blue w-full mt-4">Зберегти</button></Modal>; }
function CancelModal({ onClose, onSubmit, busy }) { const [reason, setReason] = useState(cancelReasons[0]), [comment, setComment] = useState(''); return <Modal title="Скасувати замовлення" onClose={onClose} top><div className="space-y-3"><Sel label="Причина" value={reason} onChange={setReason} options={cancelReasons.map((r) => [r, r])} /><textarea className={`${field} min-h-[90px]`} value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Коментар" /><button disabled={busy} onClick={() => onSubmit({ reason, comment })} className="bg-rose-600 text-white rounded-xl px-5 py-3 text-xs font-black uppercase w-full">Скасувати</button></div></Modal>; }
function OrderForm({ form, setForm, onSubmit, busy }) { return <form onSubmit={onSubmit} className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Input required label="Покупець" value={form.client} onChange={(v) => setForm({ ...form, client: v })} /><Input required label="Телефон" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })} /><Input label="Номер авто" value={form.plate} onChange={(v) => setForm({ ...form, plate: v.toUpperCase() })} /><Input label="VIN" value={form.vin_code} onChange={(v) => setForm({ ...form, vin_code: v.toUpperCase() })} /><Sel label="Джерело" value={form.source} onChange={(v) => setForm({ ...form, source: v })} options={['Телефон', 'Сайт', 'Telegram', 'Instagram', 'OLX', 'Магазин'].map((v) => [v, v])} /><Sel label="Доставка" value={form.delivery_type} onChange={(v) => setForm({ ...form, delivery_type: v })} options={[['pickup', 'Самовивіз'], ['nova_poshta', 'Нова пошта'], ['courier', 'Курʼєр']]} /></div><button disabled={busy} className="btn-blue w-full">Створити</button></form>; }
function QuickForm({ form, setForm, onSubmit, busy }) { return <form onSubmit={onSubmit} className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Input required label="Назва" value={form.name} onChange={(v) => setForm({ ...form, name: v })} /><Input label="Бренд" value={form.brand} onChange={(v) => setForm({ ...form, brand: v })} /><Input label="Артикул" value={form.article} onChange={(v) => setForm({ ...form, article: v })} /><Input label="Постачальник" value={form.supplier} onChange={(v) => setForm({ ...form, supplier: v })} /><Input label="Закупка" value={form.buy_price} onChange={(v) => setForm({ ...form, buy_price: v })} /><Input required label="Продаж" value={form.sell_price} onChange={(v) => setForm({ ...form, sell_price: v })} /><Input label="Кількість" value={form.quantity} onChange={(v) => setForm({ ...form, quantity: v })} /><Sel label="Оплата" value={form.payment_status} onChange={(v) => setForm({ ...form, payment_status: v })} options={[['paid', 'Оплачено'], ['unpaid', 'Не оплачено'], ['cod', 'Післяплата'], ['debt', 'Борг']]} /></div><button disabled={busy} className="btn-green w-full">Продати і відкрити чек</button></form>; }
function Modal({ title, onClose, children, top }) { return <div className={`fixed inset-0 bg-slate-900/60 backdrop-blur-sm ${top ? 'z-[90]' : 'z-[70]'} overflow-y-auto p-4`}><div className="bg-white rounded-3xl w-full max-w-2xl mx-auto my-8 p-5 md:p-6 relative shadow-2xl"><button onClick={onClose} className="absolute top-4 right-4 p-2 bg-slate-100 rounded-xl"><X size={18} /></button><h2 className="text-2xl font-black uppercase mb-5 pr-10">{title}</h2>{children}</div></div>; }
function Panel({ title, children }) { return <div className="bg-white border rounded-3xl p-4 shadow-sm"><h3 className="font-black uppercase mb-3 text-sm">{title}</h3>{children}</div>; }
function Notice({ message, onClose }) { return <div className="mb-5 rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700 flex justify-between"><span>{message}</span><button onClick={onClose}><XCircle size={16} /></button></div>; }
function Metric({ label, value, positive }) { return <div className="bg-slate-50 border rounded-2xl p-3"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className={`font-black text-sm ${positive === undefined ? 'text-slate-800' : positive ? 'text-emerald-600' : 'text-rose-600'}`}>{value}</p></div>; }
function Info({ label, value }) { return <p className="text-sm mb-3"><span className="font-black text-slate-400 uppercase text-[10px] block">{label}</span><span className="font-bold break-all">{value || '-'}</span></p>; }
function Badge({ children }) { return <span className="text-[10px] font-black uppercase px-2 py-1 rounded-lg bg-white text-slate-600 border">{children}</span>; }
function Empty({ text }) { return <div className="text-center text-slate-400 text-xs font-black uppercase py-8 bg-white/60 rounded-2xl">{text}</div>; }
function IconBtn({ icon, title, onClick, danger }) { return <button type="button" onClick={onClick} title={title} className={`bg-white border rounded-xl p-2 ${danger ? 'text-rose-500 border-rose-100' : 'text-slate-500'}`}>{icon}</button>; }
function F({ value, onChange, placeholder, required }) { return <input required={required} placeholder={placeholder} value={value} onChange={(e) => onChange(e.target.value)} className={field} />; }
function Input({ label, value, onChange, required }) { return <label className="block"><span className="text-[10px] font-black uppercase text-slate-500 mb-1.5 block">{label}</span><input required={required} value={value || ''} onChange={(e) => onChange(e.target.value)} className={field} /></label>; }
function Labeled({ label, value, onBlur }) { const [v, setV] = useState(value); useEffect(() => setV(value), [value]); return <label className="block mb-2"><span className="text-[10px] font-black uppercase text-slate-500 mb-1.5 block">{label}</span><input value={v || ''} onChange={(e) => setV(e.target.value)} onBlur={() => onBlur(v)} className={field} /></label>; }
function Sel({ label, value, onChange, options }) { return <label className="block mb-2"><span className="text-[10px] font-black uppercase text-slate-500 mb-1.5 block">{label}</span><select value={value || ''} onChange={(e) => onChange(e.target.value)} className={field}>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function PayMini({ label, value, bad, good }) { return <div className="bg-white/80 border border-white rounded-xl p-2"><p className="text-[9px] font-black uppercase text-slate-400">{label}</p><p className={`text-sm font-black ${bad ? 'text-rose-600' : good ? 'text-emerald-600' : 'text-slate-800'}`}>{value}</p></div>; }
function Mac({ icon, onClick, danger, ok, title }) { return <button title={title} onClick={onClick} className={`w-9 h-9 rounded-full flex items-center justify-center border ${danger ? 'bg-rose-50 text-rose-600 border-rose-100' : ok ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-amber-50 text-amber-600 border-amber-100'}`}>{icon}</button>; }
