export const VEHICLE_MAKES = Object.freeze([
  'Abarth',
  'AC',
  'Acura',
  'Aiways',
  'Aixam',
  'Alfa Romeo',
  'Alpina',
  'Alpine',
  'AMC',
  'Ariel',
  'Aro',
  'Aspark',
  'Aston Martin',
  'Audi',
  'Austin',
  'Autobianchi',
  'Avatr',
  'BAIC',
  'Baojun',
  'BAW',
  'Belgee',
  'Bentley',
  'Bestune',
  'BMW',
  'Bogdan',
  'Bollinger',
  'Borgward',
  'Brilliance',
  'Bugatti',
  'Buick',
  'BYD',
  'Cadillac',
  'Caterham',
  'Changan',
  'Changhe',
  'Chery',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Cupra',
  'Dacia',
  'Daewoo',
  'DAF',
  'Daihatsu',
  'Datsun',
  'Deepal',
  'DeLorean',
  'Denza',
  'De Tomaso',
  'DFSK',
  'Dodge',
  'Dongfeng',
  'Donkervoort',
  'DS Automobiles',
  'Eagle',
  'Ebro',
  'Exeed',
  'FAW',
  'Ferrari',
  'Fiat',
  'Fisker',
  'Ford',
  'Forthing',
  'Foton',
  'Freightliner',
  'GAC',
  'GAZ',
  'Geely',
  'Genesis',
  'Geo',
  'GMC',
  'Great Wall',
  'Haval',
  'Hino',
  'Holden',
  'Honda',
  'Hongqi',
  'Hummer',
  'Hyundai',
  'IM Motors',
  'Ineos',
  'Infiniti',
  'International',
  'Isuzu',
  'Iveco',
  'JAC',
  'Jaecoo',
  'Jaguar',
  'Jeep',
  'Jetour',
  'Jetta',
  'KAMAZ',
  'Karma',
  'Kenworth',
  'Kia',
  'Koenigsegg',
  'KrAZ',
  'KTM',
  'Lada',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Leapmotor',
  'Lexus',
  'Li Auto',
  'Ligier',
  'Lincoln',
  'Lotus',
  'LuAZ',
  'Lucid',
  'Luxgen',
  'Lynk & Co',
  'Mack',
  'Mahindra',
  'MAN',
  'Maserati',
  'Maxus',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mercury',
  'MG',
  'MINI',
  'Mitsubishi',
  'Morgan',
  'Moskvich',
  'Neta',
  'NIO',
  'Nissan',
  'Noble',
  'Oldsmobile',
  'Omoda',
  'Opel',
  'Ora',
  'Pagani',
  'Peugeot',
  'Peterbilt',
  'Plymouth',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Proton',
  'Puch',
  'RAM',
  'Ravon',
  'Renault',
  'Renault Trucks',
  'Rezvani',
  'Rimac',
  'Rivian',
  'Roewe',
  'Rolls-Royce',
  'Rover',
  'Rox',
  'Saab',
  'SAIC',
  'Saturn',
  'Scania',
  'Scion',
  'SEAT',
  'Seres',
  'Simca',
  'Škoda',
  'Skywell',
  'Smart',
  'Soueast',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Talbot',
  'Tank',
  'Tata',
  'Tatra',
  'Tesla',
  'Tofaş',
  'Toyota',
  'Trabant',
  'TVR',
  'UAZ',
  'Vauxhall',
  'VinFast',
  'Volkswagen',
  'Volvo',
  'Voyah',
  'Wartburg',
  'Weltmeister',
  'Wey',
  'Wiesmann',
  'Wuling',
  'Xiaomi',
  'Xpeng',
  'Yangwang',
  'Zastava',
  'ZAZ',
  'Zeekr',
  'Zotye',
]);

export function normalizeVehicleMake(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLocaleLowerCase('uk-UA')
    .replace(/[^a-zа-яіїєґ0-9]+/g, ' ')
    .trim();
}

function vehicleMakeScore(make, rawQuery) {
  const candidate = normalizeVehicleMake(make);
  const query = normalizeVehicleMake(rawQuery);
  if (!query) return 0;
  if (candidate === query) return 0;
  if (candidate.startsWith(query)) return 1;
  if (candidate.split(' ').some((word) => word.startsWith(query))) return 2;
  if (candidate.includes(query)) return 3;
  return Number.POSITIVE_INFINITY;
}

export function searchVehicleMakes(makes, query) {
  const safeMakes = Array.isArray(makes) ? makes : [];
  if (!normalizeVehicleMake(query)) return safeMakes;

  return safeMakes
    .map((make, index) => ({ make, index, score: vehicleMakeScore(make, query) }))
    .filter((result) => Number.isFinite(result.score))
    .sort((left, right) => left.score - right.score || left.index - right.index)
    .map((result) => result.make);
}
